import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import FilterSection from "@/components/filter_section/filterSection";
import { useEffect, useState } from "react";
import { Job } from "@/types";
import axios, { AxiosRequestConfig } from "axios";
import JobListings from "@/components/job_listings/jobListings";
import { Icons } from "@/components/ui_components/Icons";
import { useAppSelector } from "@/hooks/redux_hooks";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const [ jobs, setJobs ] = useState<Job[]>( [] )
  console.log(jobs)
  const [ totalCount, setTotalCount ] = useState<number>( 0 )
  const [ offset, setOffset ] = useState<number>( 0 );
  
  const filters = useAppSelector((state) => state.filters);
	console.log(filters);

  const fetchData = async (newOffset: number) => {
		try {
			const response = await axios.post("/api/fetch_job_listings", {
				limit: 10,
				offset: newOffset,
			});
			if (response) {
				const data = response.data.data;
				setJobs((prevJobs) => [...prevJobs, ...data.jdList]);
        setTotalCount( data.totalCount );
        setOffset(newOffset);
			}
		} catch (error) {
			console.log(error);
		} finally {
		}
	};
  
  useEffect( () => {
    fetchData(0)
  }, [] )
  
  const loadMoreJobs = () => {
		const newOffset = offset + 10;
		fetchData(newOffset);
	};

  return (
		<>
			<Head>
				<title>Find jobs via Weekday</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='https://www.google.com/s2/favicons?domain=https://jobs.weekday.works/'
				/>
			</Head>
			<main className={`${styles.main} ${inter.className} w-[90%] mx-auto`}>
				<FilterSection />
				{jobs.length > 0 ? (
					<>
						<JobListings data={jobs} />
						<div className='w-full flex items-center justify-center py-6'>
              <button
                onClick={loadMoreJobs}
                className="flex items-center justify-center space-x-1 font-semibold hover:scale-105 active:scale-95 duration-200"
              >
                <Icons.loader className="text-lg"/>
								<h1>Load More</h1>
							</button>
						</div>
					</>
				) : (
					<></>
				)}
			</main>
		</>
	);
}
